### ISSUE TITLE
Keymaps doesn't seem to do anything

### ISSUE THREAD

**Issue by fredrikaverpil** [mikkasendke/sessionizer.wezterm#2]
Hi! 👋

I'm on macOS and I've tried both using the default installation method (with default keymaps) and I've tried to use custom keymaps, as described in your README. Not sure what's wrong as I don't get any feedback whatsoever when hitting the keymaps.

I do, however, see the following is available, but I think this is just because I have the keymaps defined:

<img width="1082" alt="Screenshot 2024-10-19 at 12 00 56" src="https://github.com/user-attachments/assets/8f6d8706-1650-4c1c-a7e7-137dd45733c5">

This is what I have right now: https://github.com/fredrikaverpil/dotfiles/pull/165

Do you have any tips for me in terms of how to debug this?
How can I make sure the lua code is even downloaded/called?

**Comment by mikkasendke** [comment]
Hey, thank you for opening the issue, I will look into it later today

**Comment by fredrikaverpil** [comment]
No stress 😄

**Comment by mikkasendke** [comment]
Well unfortunately I am unable to reproduce the issue using your config. As for if the lua is even downloaded/called, this is the case else the events would not show up, the source for the plugin should be in `~/.local/share/wezterm/plugins/httpssCssZssZsgithubsDscomsZsmikkasendkesZssessionizersDswezterm` (I think it should be the same on macos). What could be helpful is if you could take a look at your debug overlay in wezterm (ctrl+shift+L) and then trigger the event using ctrl+shift+S or manually using ctrl+shift+p. Then we could narrow down the issue probably (note: sometimes you need to press enter there for new logs to appear)

**Comment by mikkasendke** [comment]
So it might be something macos specific

**Comment by fredrikaverpil** [comment]
Okay, here's something:

```
Debug Overlay
wezterm version: 20240203-110809-5046fc22 aarch64-apple-darwin
Window Environment: macOS 15.0.1 (24A348)
Lua Version: Lua 5.4
OpenGL: Apple M1 4.1 Metal - 89.3
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
19:11:24.032 ERROR wezterm_gui::termwindow > while processing sessionizer.show event: No such file or directory (os error 2)
stack traceback:
        [C]: in local 'poll'
        [string "?"]:4: in function 'wezterm.run_child_process'
        ...esZssessionizersDswezterm/plugin/sessionizer/entries.lua:70: in upvalue 'apply_commands'
        ...esZssessionizersDswezterm/plugin/sessionizer/entries.lua:90: in function 'sessionizer.entries.get_entries'
        ...omsZsmikkasendkesZssessionizersDswezterm/plugin/init.lua:21: in function <...omsZsmikkasendkesZssessionizersDswezterm/plugin/init.lua:19>

>
```

Could it be that it can't find `fd`?
I do have it installed:

```bash
❯ which fd
/opt/homebrew/bin/fd
```

**Comment by mikkasendke** [comment]
Seems like it, I just added a small option (`sessionizer.config.command_options.fd_path`) which should be a quick fix for now (maybe we'll run `which fd` and take that as the path but yeah) You can either delete the downloaded plugin or run require "wezterm".plugin.update_all() to update and try it

**Comment by fredrikaverpil** [comment]
Nice, that did it. 👍

**Comment by mikkasendke** [comment]
cool

**Comment by celarye** [comment]
> Seems like it, I just added a small option (`sessionizer.config.command_options.fd_path`) which should be a quick fix for now (maybe we'll run `which fd` and take that as the path but yeah) You can either delete the downloaded plugin or run require "wezterm".plugin.update_all() to update and try it

Could this be added to the README? Using Homebrew for installing tools like fd is very common on macOS.

**Comment by mikkasendke** [comment]
Yes I will add a small note, thanks for the suggestion. On the "v2" branch which changes a lot it will be found automatically though already but I guess for  the time being this is a good idea, thanks
